### ISSUE TITLE
Doesn't appear to work

### ISSUE THREAD

**Issue by SheepCommander** [cyyynthia/groupdm-nuke-defender#1]
Upon having a friend add myself to 5 groups in 30 seconds (I timed it) nothing happened (installing it seems to have also caused an increase of console errors, although I'm too stupid to point out any speciifc error that relates to the plugin)

**Comment by cyyynthia** [comment]
The plugin has been tested and works. The only issue was with the modal which lead to a crash but this has been fixed.

**Comment by SheepCommander** [comment]
I see
